### PR TITLE
added uiValidateAsync directive for Async validations

### PR DESCRIPTION
**Pull request by ejmarino**
(already done in ui-utils project) integration with angular 1.3+ own's validation async system (works with $pending variables)
This time the build completes fine.
Check it on: http://embed.plnkr.co/HpqX6b1hYBfq7zDrHCZp/preview

### CODE REVIEW

**Comment by PowerKiKi** [comment]
Thank you for taking time to resubmit your work. Could you add an example on the demo page please ? Then I'll merge.

**Comment by ejmarino** [comment]
Ok I'll will. Thank you.
Sorry for the off topic, but I don't know how to reach you in another place. 
I've developed a little publish/subscribe messaging service for angular [on github](https://github.com/ejmarino/angular-ms). I would like to make it part of angular-ui/ui-utils. How can I do it? It is possible? Thanks.

**Comment by ejmarino** [comment]
Demo page is updated.

**Comment by PowerKiKi** [comment]
Released in [1.1.0](https://github.com/angular-ui/ui-validate/releases/tag/v1.1.0)

**Comment by PowerKiKi** [comment]
For `angular-ms`, "ui-utils" does not really exist anymore. But I guess you could still be part of AngularUI. The first thing to do would be to use Angular UI convention for the name. So rename into something like `ui-ms`. The module itself would probably be `ui.ms` instead of `ngms`.

**Pull request closed without merging**
