### PR TITLE
Added support for watch object equality flag and watch collection

### PR DESCRIPTION
**Pull request by r0b-**
Didn't test all variations but I mostly copied existing code so it should work.

### CODE REVIEW

**Comment by PowerKiKi** [comment]
Thanks for the PR. Could you please provide either documentation or tests ? (both would be awesome)

**Comment by r0b-** [comment]
Where should I put the documentation? demo.html?

**Comment by r0b-** [comment]
Added all awesomeness :-)

**Comment by PowerKiKi** [comment]
Great, thanks !

**Comment by PowerKiKi** [comment]
released as 1.2.0

**Pull request merged**
